server:
  port: 8002
spring:
  application:
    name: shenggongjie-es
  profiles:
    active: test
  cloud:
    nacos:
      config:
        server-addr: 39.101.137.246:8848
        username: nacos
        password: turing12345
      discovery:
        server-addr: 39.101.137.246:8848
        username: nacos
        password: turing12345
  config:
    import:
      - nacos:${spring.application.name}-${spring.profiles.active}.yml
