server:
  port: 8001
spring:
  application:
    name: eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
    fetch-registry: false
    register-with-eureka: false